name: Android CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/android.yml
      - android/**
  pull_request:
    paths:
      - .github/workflows/android.yml
      - android/**

jobs:
  build_signed_debug_apk:
    name: Build and Sign App Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build with Gradle
        id: gradle_build_debug
        run: ./android/gradlew assembleDebug -p android

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
  send_debug_apk:
    name: Send Debug APK
    runs-on: ubuntu-latest
    needs: build_signed_debug_apk
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Download debug apk
        uses: actions/download-artifact@v4
        with:
          name: app-debug
          
      - name: Get the last commit message
        id: get_commit_msg
        run: |
          commit_message=$(git log -1 --pretty=format:'%s')
          echo "message=$commit_message" >> $GITHUB_OUTPUT
          
      - name: Rename file 
        run: |
          mv android/app/build/outputs/apk/debug/app-debug.apk tool-telegram-debug.apk
          ls 

      - name: Send APK to Debug Channel Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to:  ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          document: tool-telegram-debug.apk
          disable_web_page_preview: false
          message: |
            *${{ github.actor }}* committed to [${{ github.repository }}](https://github.com/${{ github.repository }})

            Branch: *${{ github.head_ref }}*
            Commit message: `${{ steps.get_commit_msg.outputs.message }}`
            
      - name: Upload all
        uses: actions/upload-artifact@v4
        with:
          name: all-repo-now
          path: ./